-- Keep session IDs and all referencing rows; only remove the former pair uniqueness.
PRAGMA foreign_keys=OFF;
BEGIN IMMEDIATE;
CREATE TABLE app_sessions_v7(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES app_projects(id),recipient TEXT NOT NULL,title TEXT NOT NULL,read_cursor INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL);
INSERT INTO app_sessions_v7 SELECT * FROM app_sessions;
DROP TABLE app_sessions;
ALTER TABLE app_sessions_v7 RENAME TO app_sessions;
CREATE INDEX app_sessions_directory ON app_sessions(project_id,recipient,created_at);
ALTER TABLE app_tasks ADD COLUMN protocol INTEGER NOT NULL DEFAULT 0;
ALTER TABLE app_tasks ADD COLUMN revision INTEGER NOT NULL DEFAULT 0;
ALTER TABLE app_tasks ADD COLUMN initiator TEXT;
ALTER TABLE app_tasks ADD COLUMN participants TEXT NOT NULL DEFAULT '[]';
ALTER TABLE app_tasks ADD COLUMN original TEXT;
ALTER TABLE app_tasks ADD COLUMN draft TEXT NOT NULL DEFAULT '{}';
ALTER TABLE app_tasks ADD COLUMN confirmed INTEGER;
ALTER TABLE app_tasks ADD COLUMN updated_at INTEGER NOT NULL DEFAULT 0;
ALTER TABLE app_tasks ADD COLUMN next_owner TEXT;
ALTER TABLE app_tasks ADD COLUMN waiting_reason TEXT;
ALTER TABLE app_tasks ADD COLUMN archived INTEGER NOT NULL DEFAULT 0;
ALTER TABLE app_tasks ADD COLUMN seq INTEGER NOT NULL DEFAULT 0;
ALTER TABLE native_tasks ADD COLUMN workdir TEXT;
CREATE TABLE app_preferences(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE task_revisions(task_id TEXT NOT NULL REFERENCES app_tasks(id),revision INTEGER NOT NULL,original TEXT NOT NULL,draft TEXT NOT NULL,participants TEXT NOT NULL,confirmed_by TEXT,confirmed_at INTEGER,confirmation_id TEXT UNIQUE,created_at INTEGER NOT NULL,PRIMARY KEY(task_id,revision));
CREATE TABLE task_journal(id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES app_tasks(id),revision INTEGER NOT NULL,sender TEXT NOT NULL,sequence INTEGER NOT NULL,kind TEXT NOT NULL,payload TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(task_id,revision,sender,sequence));
CREATE TABLE task_questions(id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES app_tasks(id),revision INTEGER NOT NULL,execution_id TEXT,asker TEXT NOT NULL,body TEXT NOT NULL,reason TEXT NOT NULL,known TEXT NOT NULL,state TEXT NOT NULL,answer TEXT,answered_by TEXT,created_at INTEGER NOT NULL);
CREATE TABLE task_executions(id TEXT PRIMARY KEY REFERENCES tasks(id),task_id TEXT NOT NULL REFERENCES app_tasks(id),revision INTEGER NOT NULL,phase TEXT NOT NULL,state TEXT NOT NULL,round INTEGER NOT NULL DEFAULT 0,snapshot_id TEXT,previous_id TEXT,recovery_reason TEXT,question_id TEXT,created_at INTEGER NOT NULL);
CREATE TABLE task_bindings(task_id TEXT NOT NULL REFERENCES app_tasks(id),revision INTEGER NOT NULL,workdir TEXT NOT NULL,roots TEXT NOT NULL,PRIMARY KEY(task_id,revision));
CREATE TABLE task_snapshots(id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES app_tasks(id),revision INTEGER NOT NULL,member TEXT NOT NULL,directory TEXT NOT NULL,manifest TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE task_candidates(task_id TEXT NOT NULL,revision INTEGER NOT NULL,member TEXT NOT NULL,result TEXT NOT NULL,PRIMARY KEY(task_id,revision,member));
CREATE TABLE task_jobs(id TEXT PRIMARY KEY,task_id TEXT NOT NULL,revision INTEGER NOT NULL,kind TEXT NOT NULL,payload TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,error TEXT,created_at INTEGER NOT NULL);
CREATE TABLE task_model_attempts(id TEXT PRIMARY KEY,task_id TEXT NOT NULL,revision INTEGER NOT NULL,stage TEXT NOT NULL,attempt INTEGER NOT NULL,state TEXT NOT NULL,response TEXT,error TEXT,created_at INTEGER NOT NULL);
CREATE TABLE task_settings(singleton INTEGER PRIMARY KEY CHECK(singleton=1),max_rounds INTEGER NOT NULL DEFAULT 12,max_no_progress INTEGER NOT NULL DEFAULT 3,max_retries INTEGER NOT NULL DEFAULT 3,max_files INTEGER NOT NULL DEFAULT 40,max_bytes INTEGER NOT NULL DEFAULT 2097152);
INSERT INTO task_settings(singleton) VALUES(1);
CREATE TABLE task_system_events(id TEXT PRIMARY KEY,kind TEXT NOT NULL,payload TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE task_fact_outbox(id TEXT PRIMARY KEY,payload TEXT NOT NULL,sent INTEGER NOT NULL DEFAULT 0);
-- Old executions keep their evidence. Their scheduler is gated until explicit recovery.
CREATE TABLE legacy_holds(kind TEXT NOT NULL,id TEXT NOT NULL,reason TEXT NOT NULL,PRIMARY KEY(kind,id));
INSERT INTO legacy_holds SELECT 'native',task_id,'升级前执行关联不完整；检查证据后显式恢复' FROM native_tasks WHERE reported=0;
INSERT INTO legacy_holds SELECT 'workflow',id,'升级前任务保留旧授权；检查证据后显式恢复' FROM workflows WHERE state NOT IN ('completed','stopped','failed');
INSERT INTO legacy_holds SELECT 'app',id,'previous state: ' || state FROM app_tasks WHERE state NOT IN ('completed','stopped','cancelled');
UPDATE app_tasks SET state='needs_attention' WHERE state NOT IN ('completed','stopped','cancelled');
UPDATE app_tasks SET error=COALESCE(error || '；','') || '历史信息不足：无新协议意图确认记录；检查旧证据后恢复' WHERE state='needs_attention';
UPDATE app_tasks SET updated_at=created_at;
PRAGMA user_version=7;
COMMIT;
PRAGMA foreign_keys=ON;
